set1= set()
print(set1)
set1 = set("krishu")
print(set1)
String= set('krishu')
print(String)
set1 = set(['k', 'r',1,3, 'k',4,'r'])
print(set1)
set1.add(7)
print(set1)
set1.update('kri')
print(set1)
print("remove element")
set1.remove(4)
set1.discard(1)
print(set1)
set1.clear()
print(set1)

#FrozenSet  can't be changed while set can be
String = 'krishika'
Frozen= frozenset(String)
print(String)
print(Frozen)
String='12345678'
print(String)
print(Frozen)

set1 = set('krishu')
set2 = set('krishika')
print('intersection',set1.intersection(set2))
print('union', set1.union(set2))
print('difference', set1.difference(set2))
print('symmetric difference', set1.symmetric_difference(set2))
print('subset', set2.issubset(set1))
print('superset', set1.issuperset(set2))